name: jupyplay
channels:
  - fastai
  - conda-forge
dependencies:
  - black
  - dask
  - dvc
  - fastcore
  - ipykernel
  - ipywidgets
  - joblib
  - matplotlib
  - more-itertools
  - nbdev=2.*
  - pandapower
  - pandas=1.*
  # - platformdirs>=3.1 # pinned until dvc fixes feedsstock
  - pyarrow=11.*
  - python-benedict
  - python=3.11
  - scienceplots
  - seaborn
  - sympy
  - tqdm