name: jupyplay
channels:
  - fastai
  - conda-forge
dependencies:
  - black
  - fastcore
  - ipykernel
  - ipywidgets
  - joblib
  - matplotlib
  - more-itertools
  - nbdev=2.*
  - pandapower
  - pandas=1.*
  - pyarrow=11.*
  - python-benedict
  - python=3.11
  - seaborn
  - sympy
  - tqdm