# AUTOGENERATED! DO NOT EDIT! File to edit: ../../11_npg.ipynb.

# %% auto 0
__all__ = []

# %% ../../11_npg.ipynb 3
import pandas as pd
import pyarrow.dataset as ds
import seaborn as sns
from fastcore.all import *
